//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BubuEntities : DbContext
    {
        public BubuEntities()
            : base("name=BubuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountActivation> AccountActivations { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<BusienssClubNewsInfo> BusienssClubNewsInfoes { get; set; }
        public DbSet<BusinessActivityMessageType> BusinessActivityMessageTypes { get; set; }
        public DbSet<BusinessClub> BusinessClubs { get; set; }
        public DbSet<BusinessClubActivity> BusinessClubActivities { get; set; }
        public DbSet<BusinessClubActivityComment> BusinessClubActivityComments { get; set; }
        public DbSet<BusinessClubActivityDetail> BusinessClubActivityDetails { get; set; }
        public DbSet<BusinessClubJoinRequest> BusinessClubJoinRequests { get; set; }
        public DbSet<BusinessClubMember> BusinessClubMembers { get; set; }
        public DbSet<Commencement> Commencements { get; set; }
        public DbSet<CompanyAbout> CompanyAbouts { get; set; }
        public DbSet<CompanyInformation> CompanyInformations { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<DocumentCategory> DocumentCategories { get; set; }
        public DbSet<DocumentFormatAllow> DocumentFormatAllows { get; set; }
        public DbSet<DocumentUpload> DocumentUploads { get; set; }
        public DbSet<Domicile> Domiciles { get; set; }
        public DbSet<EmploymentType> EmploymentTypes { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<formatAllow_old> formatAllow_old { get; set; }
        public DbSet<Hobby> Hobbies { get; set; }
        public DbSet<JobType> JobTypes { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Level> Levels { get; set; }
        public DbSet<Qualification> Qualifications { get; set; }
        public DbSet<QualificationCategory> QualificationCategories { get; set; }
        public DbSet<Reference> References { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserHobby> UserHobbies { get; set; }
        public DbSet<UserInbox> UserInboxes { get; set; }
        public DbSet<UserLanguage> UserLanguages { get; set; }
        public DbSet<UserMessageDetail> UserMessageDetails { get; set; }
        public DbSet<UserQualification> UserQualifications { get; set; }
        public DbSet<UserReference> UserReferences { get; set; }
        public DbSet<UserSkill> UserSkills { get; set; }
        public DbSet<UserWorkExperience> UserWorkExperiences { get; set; }
        public DbSet<Vacancy> Vacancies { get; set; }
        public DbSet<VacancyApply> VacancyApplies { get; set; }
        public DbSet<WorkExperience> WorkExperiences { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
