//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessClub
    {
        public BusinessClub()
        {
            this.BusienssClubNewsInfoes = new HashSet<BusienssClubNewsInfo>();
            this.BusinessClubActivities = new HashSet<BusinessClubActivity>();
            this.BusinessClubMembers = new HashSet<BusinessClubMember>();
        }
    
        public int BusinessClubId { get; set; }
        public string BusinessClubName { get; set; }
        public string Purpose { get; set; }
        public string About { get; set; }
        public string ContentType { get; set; }
        public byte[] ContentData { get; set; }
        public string format { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public int UserCreatedId { get; set; }
    
        public virtual ICollection<BusienssClubNewsInfo> BusienssClubNewsInfoes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BusinessClubActivity> BusinessClubActivities { get; set; }
        public virtual ICollection<BusinessClubMember> BusinessClubMembers { get; set; }
    }
}
