//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCategory
    {
        public DocumentCategory()
        {
            this.DocumentFormatAllows = new HashSet<DocumentFormatAllow>();
            this.DocumentUploads = new HashSet<DocumentUpload>();
        }
    
        public int DocumentCategoryid { get; set; }
        public string DocumentCategoryName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<DocumentFormatAllow> DocumentFormatAllows { get; set; }
        public virtual ICollection<DocumentUpload> DocumentUploads { get; set; }
    }
}
