//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationCategory
    {
        public QualificationCategory()
        {
            this.UserQualifications = new HashSet<UserQualification>();
            this.Vacancies = new HashSet<Vacancy>();
        }
    
        public int QualificationCategoryId { get; set; }
        public string QualificationCategoryName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<UserQualification> UserQualifications { get; set; }
        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }
}
