//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AccountActivations = new HashSet<AccountActivation>();
            this.BusienssClubNewsInfoes = new HashSet<BusienssClubNewsInfo>();
            this.BusinessClubs = new HashSet<BusinessClub>();
            this.BusinessClubActivities = new HashSet<BusinessClubActivity>();
            this.BusinessClubActivityComments = new HashSet<BusinessClubActivityComment>();
            this.BusinessClubActivityDetails = new HashSet<BusinessClubActivityDetail>();
            this.BusinessClubMembers = new HashSet<BusinessClubMember>();
            this.CompanyInformations = new HashSet<CompanyInformation>();
            this.DocumentUploads = new HashSet<DocumentUpload>();
            this.UserHobbies = new HashSet<UserHobby>();
            this.UserInboxes = new HashSet<UserInbox>();
            this.UserInboxes1 = new HashSet<UserInbox>();
            this.UserLanguages = new HashSet<UserLanguage>();
            this.UserMessageDetails = new HashSet<UserMessageDetail>();
            this.UserMessageDetails1 = new HashSet<UserMessageDetail>();
            this.UserQualifications = new HashSet<UserQualification>();
            this.UserReferences = new HashSet<UserReference>();
            this.UserSkills = new HashSet<UserSkill>();
            this.VacancyApplies = new HashSet<VacancyApply>();
            this.UserWorkExperiences = new HashSet<UserWorkExperience>();
        }
    
        public int Userid { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNumber { get; set; }
        public byte[] VersionNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public string ContentType { get; set; }
        public byte[] ContentData { get; set; }
        public string format { get; set; }
        public string ProfileEmailAddress { get; set; }
        public string UserDomicile { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsMarried { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CommencementID { get; set; }
        public Nullable<int> DomicileId { get; set; }
        public string ProfileURL { get; set; }
        public string UserAddress { get; set; }
    
        public virtual ICollection<AccountActivation> AccountActivations { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual ICollection<BusienssClubNewsInfo> BusienssClubNewsInfoes { get; set; }
        public virtual ICollection<BusinessClub> BusinessClubs { get; set; }
        public virtual ICollection<BusinessClubActivity> BusinessClubActivities { get; set; }
        public virtual ICollection<BusinessClubActivityComment> BusinessClubActivityComments { get; set; }
        public virtual ICollection<BusinessClubActivityDetail> BusinessClubActivityDetails { get; set; }
        public virtual ICollection<BusinessClubMember> BusinessClubMembers { get; set; }
        public virtual Commencement Commencement { get; set; }
        public virtual ICollection<CompanyInformation> CompanyInformations { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<DocumentUpload> DocumentUploads { get; set; }
        public virtual Domicile Domicile { get; set; }
        public virtual ICollection<UserHobby> UserHobbies { get; set; }
        public virtual ICollection<UserInbox> UserInboxes { get; set; }
        public virtual ICollection<UserInbox> UserInboxes1 { get; set; }
        public virtual ICollection<UserLanguage> UserLanguages { get; set; }
        public virtual ICollection<UserMessageDetail> UserMessageDetails { get; set; }
        public virtual ICollection<UserMessageDetail> UserMessageDetails1 { get; set; }
        public virtual ICollection<UserQualification> UserQualifications { get; set; }
        public virtual ICollection<UserReference> UserReferences { get; set; }
        public virtual ICollection<UserSkill> UserSkills { get; set; }
        public virtual ICollection<VacancyApply> VacancyApplies { get; set; }
        public virtual ICollection<UserWorkExperience> UserWorkExperiences { get; set; }
    }
}
