//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessageDetail
    {
        public int UserMessageId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsActiveFromSender { get; set; }
        public Nullable<bool> IsActiveFromReceiver { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
