//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReference
    {
        public int UserReferenceId { get; set; }
        public int UserId { get; set; }
        public int ReferenceId { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceContactNo { get; set; }
        public string ReferenceCompany { get; set; }
        public string ReferencePosition { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Reference Reference { get; set; }
        public virtual User User { get; set; }
    }
}
