//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkExperience
    {
        public int UserWorkExperienceid { get; set; }
        public int UserId { get; set; }
        public string Company { get; set; }
        public string JobFunction { get; set; }
        public string Position { get; set; }
        public string JobLocation { get; set; }
        public string Description { get; set; }
        public string Institution { get; set; }
        public System.DateTime JobFrom { get; set; }
        public Nullable<System.DateTime> JobTo { get; set; }
        public bool IsCurrentJob { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
