//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOClassLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public Vacancy()
        {
            this.UserInboxes = new HashSet<UserInbox>();
            this.VacancyApplies = new HashSet<VacancyApply>();
        }
    
        public int VacancyId { get; set; }
        public int CompanyId { get; set; }
        public bool IsPrivate { get; set; }
        public string JobTitle { get; set; }
        public string JobFunction { get; set; }
        public string JobDetail { get; set; }
        public int JobTypeId { get; set; }
        public bool IsVacancyCompleted { get; set; }
        public string CompletedRemark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> QualificationCategoryId { get; set; }
        public Nullable<int> QualificationId { get; set; }
    
        public virtual CompanyInformation CompanyInformation { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<UserInbox> UserInboxes { get; set; }
        public virtual ICollection<VacancyApply> VacancyApplies { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual QualificationCategory QualificationCategory { get; set; }
    }
}
