//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubu_WebApp.Forms {
    
    
    public partial class Business {
        
        /// <summary>
        /// CurriculamVitaeControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bubu_WebApp.Forms.UserControls.CurriculamVitaeControl CurriculamVitaeControl;
        
        /// <summary>
        /// btnEditDocuments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnEditDocuments;
        
        /// <summary>
        /// DLSCertificate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bubu_WebApp.Forms.UserControls.DocumentListDisplayControl DLSCertificate;
        
        /// <summary>
        /// DLSDiploma control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bubu_WebApp.Forms.UserControls.DocumentListDisplayControl DLSDiploma;
        
        /// <summary>
        /// DLSOtherDocument control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bubu_WebApp.Forms.UserControls.DocumentListDisplayControl DLSOtherDocument;
    }
}
